version: '3'
services:
  web:
    container_name: ${PROJECT_NAME}-web
    build: .
    command: npm run dev
    volumes:
      - ../:/src/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
